id: P000153
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །གདུལ་ཞིང་སྣོད་བཅུད་ཀྱི་འཇིག་རྟེན་རིམ་པར་ཕྱེ་བ། །
  authors:
  - མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
  id: RDI-TOK-01-1
web_metadata:
  title:
    en: Myriad Worlds:Buddhist Cosmology in Abhidharma, Kalachakra, and Dzogchen
    bo: གདུལ་ཞིང་སྣོད་བཅུད་ཀྱི་འཇིག་རྟེན་རིམ་པར་ཕྱེ་བ།
  collection:
    en: ''
    bo: ཤེས་བྱ་ཀུན་ཁྱབ་མཛོད།–  དེབ། ༡
  author:
    en: Jamgon Kongtrul Lodro Thaye
    bo: འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
  pusblisher:
    en: Rigpe Dorje Institute
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-TOK-01-1
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-TOK-01-1.epub
  description:
    en: ཤེས་བྱ་ཀུན་ཁྱབ་མཛོད། གནས་དང་པོ།
    bo: ཤེས་བྱ་ཀུན་ཁྱབ་མཛོད། གནས་དང་པོ།
